import { JetView } from "webix-jet";
import { gradeData } from "models/user_db";


export default class GradeView extends JetView {
	config() {
		let grade_options = {
			"2": 2,
			"3": 3,
			"4": 4,
			"5": 5,
			"Н": "Н",
		};
		return {
			rows: [
				{ template: "<b>Школьный журнал учителя</b><br><br>", height: 30 },
				{
					view: "tabbar",
					multiview: true,
					options: [
						{ value: "I четверть", id: "gradeTable1", },
						{ value: "II четверть", id: "gradeTable2", },
						{ value: "III четверть", id: "gradeTable3", },
						{ value: "IV четверть", id: "gradeTable4", },
					]
				},

				{
					cells: [
						{
							view: "datatable",
							id: "gradeTable1",
							css: "webix_header_border webix_data_border",
							editable: true,
							leftSplit: 2,
							columns: [
								{ id: "fName", header: [{ text: "Ученик", css: { "text-align": "center" }, colspan: 2 }, { text: "Имя" }], sort: "text", adjust: true, minWidth: 200 },
								{ id: "lName", header: [{}, { text: "Фамилия" }], sort: "text", fillspace: true, minWidth: 200 },

								{ id: "grade01", editor: "select", options: grade_options, header: [{ content: "columnGroup", closed: true, batch: "сентябрь", groupText: "Сентябрь", colspan: 30, }, 1], width: 120, minWidth: 120 },
								{ id: "grade02", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 2], width: 120 },
								{ id: "grade03", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 3], width: 120 },
								{ id: "grade04", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 4], width: 120 },
								{ id: "grade05", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 5], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 6], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 7], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 8], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 9], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 10], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 11], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 12], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 13], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 14], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 15], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 16], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 17], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 18], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 19], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 20], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 21], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 22], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 23], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 24], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 25], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 26], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 27], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 28], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 29], width: 120 },
								{ id: "", editor: "select", options: grade_options, batch: "сентябрь", header: [{}, 30], width: 120 },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "октябрь", groupText: "Октябрь", colspan: 25, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "октябрь", header: [{}, 2] },
								{ id: "", batch: "октябрь", header: [{}, 3] },
								{ id: "", batch: "октябрь", header: [{}, 4] },
								{ id: "", batch: "октябрь", header: [{}, 5] },
								{ id: "", batch: "октябрь", header: [{}, 6] },
								{ id: "", batch: "октябрь", header: [{}, 7] },
								{ id: "", batch: "октябрь", header: [{}, 8] },
								{ id: "", batch: "октябрь", header: [{}, 9] },
								{ id: "", batch: "октябрь", header: [{}, 10] },
								{ id: "", batch: "октябрь", header: [{}, 11] },
								{ id: "", batch: "октябрь", header: [{}, 12] },
								{ id: "", batch: "октябрь", header: [{}, 13] },
								{ id: "", batch: "октябрь", header: [{}, 14] },
								{ id: "", batch: "октябрь", header: [{}, 15] },
								{ id: "", batch: "октябрь", header: [{}, 16] },
								{ id: "", batch: "октябрь", header: [{}, 17] },
								{ id: "", batch: "октябрь", header: [{}, 18] },
								{ id: "", batch: "октябрь", header: [{}, 19] },
								{ id: "", batch: "октябрь", header: [{}, 20] },
								{ id: "", batch: "октябрь", header: [{}, 21] },
								{ id: "", batch: "октябрь", header: [{}, 22] },
								{ id: "", batch: "октябрь", header: [{}, 23] },
								{ id: "", batch: "октябрь", header: [{}, 24] },
								{ id: "", batch: "октябрь", header: [{}, 25] },
							],
							on: {
								onCollectValues: function (id, req) {
									if (id == "form") {
										req.values = [
											{ id: "1а", value: "1а" },
											{ id: "1б", value: "1б" },
											{ id: "2а", value: "2а" },
											{ id: "2б", value: "2б" },
											{ id: "3а", value: "3а" },
											{ id: "3б", value: "3б" },
											{ id: "4а", value: "4а" },
											{ id: "4б", value: "4б" },
											{ id: "5а", value: "5а" },
											{ id: "5б", value: "5б" },
											{ id: "6а", value: "6а" },
											{ id: "6б", value: "6б" },
											{ id: "7а", value: "7а" },
											{ id: "7б", value: "7б" },
											{ id: "8а", value: "8а" },
											{ id: "8б", value: "8б" },
											{ id: "9а", value: "9а" },
											{ id: "9б", value: "9б" },
											{ id: "10а", value: "10а" },
											{ id: "10б", value: "10б" },
											{ id: "11а", value: "11а" },
											{ id: "11б", value: "11б" },
										]
									}
								}
							},
						},

						{
							view: "datatable",
							id: "gradeTable2",
							css: "webix_header_border webix_data_border",
							leftSplit: 2,
							columns: [
								{ id: "fName", header: [{ text: "Ученик", css: { "text-align": "center" }, colspan: 2 }, { text: "Имя" }], sort: "text", adjust: true, minWidth: 200 },
								{ id: "lName", header: [{}, { text: "Фамилия" }], sort: "text", fillspace: true, minWidth: 200 },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "ноябрь", groupText: "Ноябрь", colspan: 26, }, 5], width: 120, minWidth: 120 },
								{ id: "", batch: "ноябрь", header: [{}, 6] },
								{ id: "", batch: "ноябрь", header: [{}, 7] },
								{ id: "", batch: "ноябрь", header: [{}, 8] },
								{ id: "", batch: "ноябрь", header: [{}, 9] },
								{ id: "", batch: "ноябрь", header: [{}, 10] },
								{ id: "", batch: "ноябрь", header: [{}, 11] },
								{ id: "", batch: "ноябрь", header: [{}, 12] },
								{ id: "", batch: "ноябрь", header: [{}, 13] },
								{ id: "", batch: "ноябрь", header: [{}, 14] },
								{ id: "", batch: "ноябрь", header: [{}, 15] },
								{ id: "", batch: "ноябрь", header: [{}, 16] },
								{ id: "", batch: "ноябрь", header: [{}, 17] },
								{ id: "", batch: "ноябрь", header: [{}, 18] },
								{ id: "", batch: "ноябрь", header: [{}, 19] },
								{ id: "", batch: "ноябрь", header: [{}, 20] },
								{ id: "", batch: "ноябрь", header: [{}, 21] },
								{ id: "", batch: "ноябрь", header: [{}, 22] },
								{ id: "", batch: "ноябрь", header: [{}, 23] },
								{ id: "", batch: "ноябрь", header: [{}, 24] },
								{ id: "", batch: "ноябрь", header: [{}, 25] },
								{ id: "", batch: "ноябрь", header: [{}, 26] },
								{ id: "", batch: "ноябрь", header: [{}, 27] },
								{ id: "", batch: "ноябрь", header: [{}, 28] },
								{ id: "", batch: "ноябрь", header: [{}, 29] },
								{ id: "", batch: "ноябрь", header: [{}, 30] },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "декабрь", groupText: "Декабрь", colspan: 27, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "декабрь", header: [{}, 2] },
								{ id: "", batch: "декабрь", header: [{}, 3] },
								{ id: "", batch: "декабрь", header: [{}, 4] },
								{ id: "", batch: "декабрь", header: [{}, 5] },
								{ id: "", batch: "декабрь", header: [{}, 6] },
								{ id: "", batch: "декабрь", header: [{}, 7] },
								{ id: "", batch: "декабрь", header: [{}, 8] },
								{ id: "", batch: "декабрь", header: [{}, 9] },
								{ id: "", batch: "декабрь", header: [{}, 10] },
								{ id: "", batch: "декабрь", header: [{}, 11] },
								{ id: "", batch: "декабрь", header: [{}, 12] },
								{ id: "", batch: "декабрь", header: [{}, 13] },
								{ id: "", batch: "декабрь", header: [{}, 14] },
								{ id: "", batch: "декабрь", header: [{}, 15] },
								{ id: "", batch: "декабрь", header: [{}, 16] },
								{ id: "", batch: "декабрь", header: [{}, 17] },
								{ id: "", batch: "декабрь", header: [{}, 18] },
								{ id: "", batch: "декабрь", header: [{}, 19] },
								{ id: "", batch: "декабрь", header: [{}, 20] },
								{ id: "", batch: "декабрь", header: [{}, 21] },
								{ id: "", batch: "декабрь", header: [{}, 22] },
								{ id: "", batch: "декабрь", header: [{}, 23] },
								{ id: "", batch: "декабрь", header: [{}, 24] },
								{ id: "", batch: "декабрь", header: [{}, 25] },
								{ id: "", batch: "декабрь", header: [{}, 26] },
								{ id: "", batch: "декабрь", header: [{}, 27] },
							],
							on: {
								onCollectValues: function (id, req) {
									if (id == "form") {
										req.values = [
											{ id: "1а", value: "1а" },
											{ id: "1б", value: "1б" },
											{ id: "2а", value: "2а" },
											{ id: "2б", value: "2б" },
											{ id: "3а", value: "3а" },
											{ id: "3б", value: "3б" },
											{ id: "4а", value: "4а" },
											{ id: "4б", value: "4б" },
											{ id: "5а", value: "5а" },
											{ id: "5б", value: "5б" },
											{ id: "6а", value: "6а" },
											{ id: "6б", value: "6б" },
											{ id: "7а", value: "7а" },
											{ id: "7б", value: "7б" },
											{ id: "8а", value: "8а" },
											{ id: "8б", value: "8б" },
											{ id: "9а", value: "9а" },
											{ id: "9б", value: "9б" },
											{ id: "10а", value: "10а" },
											{ id: "10б", value: "10б" },
											{ id: "11а", value: "11а" },
											{ id: "11б", value: "11б" },
										]
									}
								}
							},
						},

						{
							view: "datatable",
							id: "gradeTable3",
							css: "webix_header_border webix_data_border",
							leftSplit: 2,
							columns: [
								{ id: "fName", header: [{ text: "Ученик", css: { "text-align": "center" }, colspan: 2 }, { text: "Имя" }], sort: "text", adjust: true, minWidth: 200 },
								{ id: "lName", header: [{}, { text: "Фамилия" }], sort: "text", fillspace: true, minWidth: 200 },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "январь", groupText: "Январь", colspan: 23, }, 9], width: 120, minWidth: 120 },
								{ id: "", batch: "январь", header: [{}, 10] },
								{ id: "", batch: "январь", header: [{}, 11] },
								{ id: "", batch: "январь", header: [{}, 12] },
								{ id: "", batch: "январь", header: [{}, 13] },
								{ id: "", batch: "январь", header: [{}, 14] },
								{ id: "", batch: "январь", header: [{}, 15] },
								{ id: "", batch: "январь", header: [{}, 16] },
								{ id: "", batch: "январь", header: [{}, 17] },
								{ id: "", batch: "январь", header: [{}, 18] },
								{ id: "", batch: "январь", header: [{}, 19] },
								{ id: "", batch: "январь", header: [{}, 20] },
								{ id: "", batch: "январь", header: [{}, 21] },
								{ id: "", batch: "январь", header: [{}, 22] },
								{ id: "", batch: "январь", header: [{}, 23] },
								{ id: "", batch: "январь", header: [{}, 24] },
								{ id: "", batch: "январь", header: [{}, 25] },
								{ id: "", batch: "январь", header: [{}, 26] },
								{ id: "", batch: "январь", header: [{}, 27] },
								{ id: "", batch: "январь", header: [{}, 28] },
								{ id: "", batch: "январь", header: [{}, 29] },
								{ id: "", batch: "январь", header: [{}, 30] },
								{ id: "", batch: "январь", header: [{}, 31] },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "февраль", groupText: "Февраль", colspan: 29, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "февраль", header: [{}, 2] },
								{ id: "", batch: "февраль", header: [{}, 3] },
								{ id: "", batch: "февраль", header: [{}, 4] },
								{ id: "", batch: "февраль", header: [{}, 5] },
								{ id: "", batch: "февраль", header: [{}, 6] },
								{ id: "", batch: "февраль", header: [{}, 7] },
								{ id: "", batch: "февраль", header: [{}, 8] },
								{ id: "", batch: "февраль", header: [{}, 9] },
								{ id: "", batch: "февраль", header: [{}, 10] },
								{ id: "", batch: "февраль", header: [{}, 11] },
								{ id: "", batch: "февраль", header: [{}, 12] },
								{ id: "", batch: "февраль", header: [{}, 13] },
								{ id: "", batch: "февраль", header: [{}, 14] },
								{ id: "", batch: "февраль", header: [{}, 15] },
								{ id: "", batch: "февраль", header: [{}, 16] },
								{ id: "", batch: "февраль", header: [{}, 17] },
								{ id: "", batch: "февраль", header: [{}, 18] },
								{ id: "", batch: "февраль", header: [{}, 19] },
								{ id: "", batch: "февраль", header: [{}, 20] },
								{ id: "", batch: "февраль", header: [{}, 21] },
								{ id: "", batch: "февраль", header: [{}, 22] },
								{ id: "", batch: "февраль", header: [{}, 23] },
								{ id: "", batch: "февраль", header: [{}, 24] },
								{ id: "", batch: "февраль", header: [{}, 25] },
								{ id: "", batch: "февраль", header: [{}, 26] },
								{ id: "", batch: "февраль", header: [{}, 27] },
								{ id: "", batch: "февраль", header: [{}, 28] },
								{ id: "", batch: "февраль", header: [{}, 29] },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "март", groupText: "Март", colspan: 20, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "март", header: [{}, 2] },
								{ id: "", batch: "март", header: [{}, 3] },
								{ id: "", batch: "март", header: [{}, 4] },
								{ id: "", batch: "март", header: [{}, 5] },
								{ id: "", batch: "март", header: [{}, 6] },
								{ id: "", batch: "март", header: [{}, 7] },
								{ id: "", batch: "март", header: [{}, 8] },
								{ id: "", batch: "март", header: [{}, 9] },
								{ id: "", batch: "март", header: [{}, 10] },
								{ id: "", batch: "март", header: [{}, 11] },
								{ id: "", batch: "март", header: [{}, 12] },
								{ id: "", batch: "март", header: [{}, 13] },
								{ id: "", batch: "март", header: [{}, 14] },
								{ id: "", batch: "март", header: [{}, 15] },
								{ id: "", batch: "март", header: [{}, 16] },
								{ id: "", batch: "март", header: [{}, 17] },
								{ id: "", batch: "март", header: [{}, 18] },
								{ id: "", batch: "март", header: [{}, 19] },
								{ id: "", batch: "март", header: [{}, 20] },
							]
						},

						{
							view: "datatable",
							id: "gradeTable4",
							css: "webix_header_border webix_data_border",
							leftSplit: 2,
							columns: [
								{ id: "fName", header: [{ text: "Ученик", css: { "text-align": "center" }, colspan: 2 }, { text: "Имя" }], sort: "text", adjust: true, minWidth: 200 },
								{ id: "lName", header: [{}, { text: "Фамилия" }], sort: "text", fillspace: true, minWidth: 200 },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "апрель", groupText: "Апрель", colspan: 30, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "апрель", header: [{}, 2] },
								{ id: "", batch: "апрель", header: [{}, 3] },
								{ id: "", batch: "апрель", header: [{}, 4] },
								{ id: "", batch: "апрель", header: [{}, 5] },
								{ id: "", batch: "апрель", header: [{}, 6] },
								{ id: "", batch: "апрель", header: [{}, 7] },
								{ id: "", batch: "апрель", header: [{}, 8] },
								{ id: "", batch: "апрель", header: [{}, 9] },
								{ id: "", batch: "апрель", header: [{}, 10] },
								{ id: "", batch: "апрель", header: [{}, 11] },
								{ id: "", batch: "апрель", header: [{}, 12] },
								{ id: "", batch: "апрель", header: [{}, 13] },
								{ id: "", batch: "апрель", header: [{}, 14] },
								{ id: "", batch: "апрель", header: [{}, 15] },
								{ id: "", batch: "апрель", header: [{}, 16] },
								{ id: "", batch: "апрель", header: [{}, 17] },
								{ id: "", batch: "апрель", header: [{}, 18] },
								{ id: "", batch: "апрель", header: [{}, 19] },
								{ id: "", batch: "апрель", header: [{}, 20] },
								{ id: "", batch: "апрель", header: [{}, 21] },
								{ id: "", batch: "апрель", header: [{}, 22] },
								{ id: "", batch: "апрель", header: [{}, 23] },
								{ id: "", batch: "апрель", header: [{}, 24] },
								{ id: "", batch: "апрель", header: [{}, 25] },
								{ id: "", batch: "апрель", header: [{}, 26] },
								{ id: "", batch: "апрель", header: [{}, 27] },
								{ id: "", batch: "апрель", header: [{}, 28] },
								{ id: "", batch: "апрель", header: [{}, 29] },
								{ id: "", batch: "апрель", header: [{}, 30] },

								{ id: "", header: [{ content: "columnGroup", closed: true, batch: "май", groupText: "Май", colspan: 29, }, 1], width: 120, minWidth: 120 },
								{ id: "", batch: "май", header: [{}, 2] },
								{ id: "", batch: "май", header: [{}, 3] },
								{ id: "", batch: "май", header: [{}, 4] },
								{ id: "", batch: "май", header: [{}, 5] },
								{ id: "", batch: "май", header: [{}, 6] },
								{ id: "", batch: "май", header: [{}, 7] },
								{ id: "", batch: "май", header: [{}, 8] },
								{ id: "", batch: "май", header: [{}, 9] },
								{ id: "", batch: "май", header: [{}, 10] },
								{ id: "", batch: "май", header: [{}, 11] },
								{ id: "", batch: "май", header: [{}, 12] },
								{ id: "", batch: "май", header: [{}, 13] },
								{ id: "", batch: "май", header: [{}, 14] },
								{ id: "", batch: "май", header: [{}, 15] },
								{ id: "", batch: "май", header: [{}, 16] },
								{ id: "", batch: "май", header: [{}, 17] },
								{ id: "", batch: "май", header: [{}, 18] },
								{ id: "", batch: "май", header: [{}, 19] },
								{ id: "", batch: "май", header: [{}, 20] },
								{ id: "", batch: "май", header: [{}, 21] },
								{ id: "", batch: "май", header: [{}, 22] },
								{ id: "", batch: "май", header: [{}, 23] },
								{ id: "", batch: "май", header: [{}, 24] },
								{ id: "", batch: "май", header: [{}, 25] },
								{ id: "", batch: "май", header: [{}, 26] },
								{ id: "", batch: "май", header: [{}, 27] },
								{ id: "", batch: "май", header: [{}, 28] },
								{ id: "", batch: "май", header: [{}, 29] },
							]
						}
					]
				},
			],
		}
	}
	init() {
		$$("gradeTable1").sync(gradeData);
		$$("gradeTable2").sync(gradeData);
		$$("gradeTable3").sync(gradeData);
		$$("gradeTable4").sync(gradeData);
	}	
}
